version: "3.8"

services:

  # The web server
  web:
    command: gunicorn -w 4 -b 0.0.0.0:80 web:app
    restart: always
    ports:
      - "8080:80"
    build:
      context: .

  # Your application (it runs main.py)
  app:
    restart: always
    build:
      context: .
